version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: iris-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: IrisDatabase
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iris-network

  backend:
    build: .
    container_name: iris-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpass
      DB_NAME: IrisDatabase
    depends_on:
      - db
    networks:
      - iris-network

networks:
  iris-network:
    driver: bridge
